version: "3.9"
services:
  terraform:
    image: hashicorp/terraform
    volumes:
      - ./infra/terraform:/expert-thinking
      - "~/.terraform.d:/root/.terraform.d"
    working_dir: /expert-thinking
    environment: 
      - ARM_CLIENT_ID=${ARM_CLIENT_ID}
      - ARM_CLIENT_SECRET=${ARM_CLIENT_SECRET}
      - ARM_SUBSCRIPTION_ID=${ARM_SUBSCRIPTION_ID}
      - ARM_TENANT_ID=${ARM_TENANT_ID}
      - TF_VAR_AZURE_OPENAI_API_KEY=${AZURE_OPENAI_API_KEY}
      - TF_VAR_AUTH_GITHUB_ID=${AUTH_GITHUB_ID}
      - TF_VAR_AUTH_GITHUB_SECRET=${AUTH_GITHUB_SECRET}
      - TF_VAR_AZURE_OPENAI_API_DEPLOYMENT_NAME=${AZURE_OPENAI_API_DEPLOYMENT_NAME}
      - TF_VAR_AZURE_OPENAI_API_VERSION=${AZURE_OPENAI_API_VERSION}
      - TF_VAR_AZURE_OPENAI_API_INSTANCE_NAME=${AZURE_OPENAI_API_INSTANCE_NAME}

  tfsec:
    image: tfsec/tfsec
    volumes:
      - ./infra/terraform:/expert-thinking
    working_dir: /infra
  infracost:
    image: infracost/infracost
    volumes:
      - .:/expert-thinking
    working_dir: /expert-thinking
    environment: 
    - INFRACOST_API_KEY=${INFRACOST_API_KEY}
    - INFRACOST_CURRENCY=${INFRACOST_CURRENCY}