name: "Terraform CI"
on: 
  workflow_call:
    secrets:
      ARM_CLIENT_ID: 
        required: true
      ARM_CLIENT_SECRET: 
        required: true
env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code" 
        uses: actions/checkout@v2
      - name: "Export environment vars"
        uses: xom9ikk/dotenv@v2.1.1
        with:
          load-mode: strict
          path: ./environments
          mode: npd 
      - name: "Validate"
        run: make validate
      - name: "Vulnerability Scan"
        run: make tfsec