name: "Release"

on: 
  workflow_call:
    inputs:
      RUNNER_NAME:
        required: true
        type: string
      COMMAND:
        type: string
        required: false
        default: "plan"
    secrets:
      ARM_CLIENT_ID: 
        required: true
      ARM_CLIENT_SECRET: 
        required: true
      INFRACOST_API_KEY: 
        required: true
      AZURE_OPENAI_API_KEY: 
        required: false
      AUTH_GITHUB_ID: 
        required: false
      AUTH_GITHUB_SECRET: 
        required: false
env:
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}
  PR_NUMBER: ${{ github.event.number }}
  AZURE_OPENAI_API_KEY: ${{ secrets.AZURE_OPENAI_API_KEY }}
  AUTH_GITHUB_ID: ${{ secrets.AUTH_GITHUB_ID }}
  AUTH_GITHUB_SECRET: ${{ secrets.AUTH_GITHUB_SECRET }}

jobs:
  deploy:
    runs-on: ${{ inputs.RUNNER_NAME }}
    steps:
      - name: "Checkout Code" 
        uses: actions/checkout@v2

      - name: "Export environment vars"
        uses: xom9ikk/dotenv@v2.1.1
        with:
          load-mode: strict
          path: ./environments
          mode: dev 

      - name: ${{ inputs.COMMAND }}
        run: make ${{ inputs.COMMAND }}

      - name: "Cost Impact"
        run: make infracost

      - name: "Get plan output"
        run: make show-txt
        if: github.event_name == 'pull_request'

      - name: Comment Pull Request
        uses: thollander/actions-comment-pull-request@v2.3.1
        if: github.event_name == 'pull_request'
        with:
          filePath: plan.txt

      - name: "Output infracost"
        if: github.event_name == 'pull_request'
        run: make infracost-out
      
      - name: Comment Pull Request with infracost
        uses: thollander/actions-comment-pull-request@v2.3.1
        if: github.event_name == 'pull_request'
        with:
          filePath: gh.md
        
